services:
  backend:
    image: kevinjulio93/finanzapp-backend:latest
    container_name: finanzapp-backend
    restart: always
    ports:
      - '4000:4000'
    environment:
      PORT: '4000'
      NODE_ENV: production
      MONGO_URI: '${MONGO_URI}'
      JWT_SECRET: '${JWT_SECRET}'
