services:
  mongodb:
    image: mongo:7
    container_name: finanzapp-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: finanzas

  backend:
    image: kevinjulio93/finanzapp-backend:prod
    pull_policy: always
    container_name: finanzapp-backend
    restart: always
    ports:
      - '4000:4000'
    environment:
      PORT: '4000'
      NODE_ENV: production
      MONGO_URI: 'mongodb://admin:admin123@mongodb:27017/finanzas?authSource=admin'
      JWT_SECRET: '${JWT_SECRET}'
      GOOGLE_CLIENT_ID: '${GOOGLE_CLIENT_ID}'
      OLLAMA_API_KEY: '${OLLAMA_API_KEY}'
      OLLAMA_MODEL: '${OLLAMA_MODEL}'
      R2_ACCESS_KEY_ID: '${R2_ACCESS_KEY_ID}'
      R2_SECRET_ACCESS_KEY: '${R2_SECRET_ACCESS_KEY}'
      R2_BUCKET_NAME: '${R2_BUCKET_NAME}'
    depends_on:
      - mongodb

volumes:
  mongodb_data:
